[build-system]
requires = [
    "setuptools >= 45",
    "wheel >= 0.30.0",
    "setuptools_scm >= 6.2",
    # Copied from https://github.com/scipy/scipy/blob/1a72584820e53d83d5f6daab6c7fbafbe9af50d7/pyproject.toml
    # NOTE: if you update this, you'll need to update install_requires in setup.py
    "Cython>=0.29.33",
    "numpy==1.22.0; platform_machine=='loongarch64'",
    "numpy==1.22.3; python_version=='3.9' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",
    "numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",
    "numpy==1.21.6; python_version=='3.9' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'",
    "numpy==1.21.6; python_version=='3.10' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'",
    "numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",
    "numpy; python_version>='3.12'",
    "numpy; python_version>='3.9' and platform_python_implementation=='PyPy'",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/qoi/_version.py"
write_to_template = "__version__ = \"{version}\""

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/tests"
build = "cp38-* cp39-* cp310-*"
# skip musl and ignore the non-standard linux builds
skip = "*-musllinux_* *s390x* *ppc64le*"
build-frontend = "build"
environment = "USE_CYTHON=1"
build-verbosity = 3